### ISSUE TITLE
Repo down

### ISSUE THREAD

**Issue by Frisch12** [aslag/glassfish-embedded#1]
Your repository (repo.tehlulz.com) is a non existing domain in google-dns server. Fix it please!

**Comment by aslag** [comment]
Sorry Frisch12, this was a failed project I've since abandoned.

After producing a working Gradle plugin I realized that running Glassfish this way limited its heap space to Gradle's, caused logging lib conflicts between the build system and application container, and other nasties. I settled on a different approach: I use a build system only for producing and publishing artifacts and build DevOps tooling for automated deployment using other tools (Python, Docker containers wrapping the runtime, etc.). I get more reliable and portable deployments that way and rely less on Gradle.
